# Further reading in https://pre-commit.com/index.html
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
        -   id: detect-aws-credentials
        -   id: detect-private-key