site_name: DevOps Course January 22
nav:
  - Home: 'index.md'
  - Linux Ex1: 'linux_ex1.md'
  - Linux Ex2: 'linux_ex2.md'
  - Git Ex1: 'git_ex1.md'
  - Python Ex1: 'python_ex1.md'
  - AWS Ex1: 'aws_ex1.md'
theme:
  name: readthedocs
