apiVersion: apps/v1
kind: Deployment
metadata:
  name: simaple-webserver
  labels:
    app: simaple-webserver
spec:
  selector:
    matchLabels:
      app: simaple-webserver
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: simaple-webserver
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: simaple-webserver
          image: # TODO your image here
---
apiVersion: v1
kind: Service
metadata:
  name: simaple-webserver-service
spec:
  selector:
    app: simaple-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
