# The version key is mandatory, and it’s always the first line at the root of the file.
# This defines the version of the Compose file format (basically the API). You should
# normally use the latest version.
version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"
  redis:
    image: "redis:alpine"
