---
- name: Harden web servers
  hosts: webserver
  become: yes
  become_method: sudo
  vars_files:
    - vars/amazon-linux.yaml
  roles:
    - sshd
    - auditd
  tasks:
#    - name: Print all available facts
#      ansible.builtin.debug:
#        var: ansible_facts

    - name: Ensure httpd is at the latest version
      become_user: root
      ansible.builtin.yum:
        name: httpd-2.4*
        state: latest
      when: ansible_facts['pkg_mgr'] == 'yum'

